title: Dessiner l'œuvre de Victor Vasarely VIII Sin-Hat-A (1974)
description: Programme en Python 3 permettant de dessiner l'œuvre de Victor Vasarely VIII Sin-Hat-A (1974)
theme: jekyll-theme-minimal
